### ISSUE TITLE
crono not maintaned - CVE-2020-26235 in time

### ISSUE THREAD

**Issue by acim** [Arnavion/k8s-openapi#109]
crono depends on vulnerable version of time and it seems not to be well maintained. Could you maybe replace it completely with some newer version of time as suggested [here](https://github.com/chronotope/chrono/issues/602#issuecomment-940218484).

**Comment by Arnavion** [comment]
We can continue discussing in https://github.com/kube-rs/kube-rs/issues/650 to keep the conversation in one place.

**Comment by Arnavion** [comment]
v0.14.0 has been released with default features disabled, as discussed in https://github.com/kube-rs/kube-rs/issues/650#issuecomment-946029033 This means that `time 0.1` is already not pulled in by default. And if `chrono` ever removes `chrono::Local` or puts it behind a feature, that too will not be pulled in by default, without needing any change in k8s-openapi.

I'm not planning on replacing `chrono` with `time` completely at this time, unless there is more reason to. `time` resolved the vuln first by making the local time API fail unconditionally, and now by making it fail [if it cannot determine that there's only one thread in the process.](https://docs.rs/time/0.3.6/src/time/sys/local_offset_at/unix.rs.html#104-112)  In my opinion this is going too far for what is reasonable for a library, especially since the trigger for this vuln is such an uncommon thing in the first place.

For posterity, [this branch](https://github.com/Arnavion/k8s-openapi/compare/master...chrono-to-time) has the change for such a switch in case I change my mind in the future.
