### ISSUE TITLE
3rd party API Generation with k8s-api-codegen?

### ISSUE THREAD

**Issue by rrichardson** [Arnavion/k8s-openapi#79]
I have a need to generate and deploy Argo workflows in Rust. There is a full swagger 2 spec for the Argo workflows here: https://github.com/argoproj/argo/blob/master/api/openapi-spec/swagger.json 

  Is it a fool's errand to try to use k8s-openapi-codegen on this?  If so, is there another approach you'd recommend? 

Thanks.

**Comment by Arnavion** [comment]
Looks like it's an aggregated server. So yes you can use `k8s-openapi-codegen-common` as a dep and `k8s-openapi-codegen`'s code as a starting point for your generator. `k8s-openapi-codegen` itself will not work since it's specifically for the Kubernetes openapi spec.

You can use https://github.com/ctron/openshift-openapi as inspiration. See the discussion in https://github.com/Arnavion/k8s-openapi/issues/24 and https://github.com/Arnavion/k8s-openapi/pull/68 for context.
